### ISSUE TITLE
Update DirectXTex to a later version

### ISSUE THREAD

**Issue by iMrShadow** [deng0/DirectXTexNet#10]
Hi! I really like the wrapper and it's been pleasure to work with it. However the DirectXTex dependency hasn't been updated for 3 years and over those years it has added some new conversion options, overall improvements and support for DXGI_FORMAT_B4G4R4A4_UNORM.

Is it possible to update it? 
Thanks

**Comment by deng0** [comment]
Nice to hear, that you like it.

I've updated the library to the DirectXTex March 6, 2024 release (DirectXTexNet 1.0.7 on Nuget).
I have made some adjustments, but have not wrapped not all of the new features.
Hopefully this works for you.

Otherwise you could take a look at another wrapper, which looks promising:
https://www.nuget.org/packages/HexaEngine.DirectXTex

**Comment by iMrShadow** [comment]
Thanks a lot! I am looking forward to the new features

Also, the wrapper that you have provided is interesting and it also has Linux support (which is a very nice feature which would be good for this wrapper).
