### ISSUE TITLE
Compression Quality

### ISSUE THREAD

**Issue by Hancapo** [deng0/DirectXTexNet#13]
There's any way to achieve a better compression using this library?
I recently noticed that NVIDIA Texture Tools can output better quality DDS

By using DXT1 and/or DXT5

**Comment by deng0** [comment]
As I understand it, when used correctly DXT1 should be the same as BC1 and DXT5 the same as BC3.
You might try BC7 for better quality, if your GPU supports it.

But because this project is just a shallow wrap of the underlying DirectXTex library you better consult their documentation https://github.com/microsoft/DirectXTex#documentation or support https://github.com/microsoft/DirectXTex#support
